/* Generated by tools/vibepulse_studio/design.py; do not hand-edit. */
#ifndef VIBEPULSE_LAYOUT_GENERATED_H
#define VIBEPULSE_LAYOUT_GENERATED_H

#define VP_SCREEN_W 240
#define VP_SCREEN_H 240
#define VP_SAFE_X 16
#define VP_CONTENT_W 208
#define VP_PROVIDER_Y 10
#define VP_QUOTA_Y 51
#define VP_PERCENT_Y 81
#define VP_PERCENT_FONT_PX 84
#define VP_BAR_Y 152
#define VP_BAR_H 12
#define VP_RESET_Y 174
#define VP_STATUS_Y 202
#define VP_STATUS_H 36

#define VP_COLOR_BACKGROUND 0x000000
#define VP_COLOR_TEXT 0xFFFFFF
#define VP_COLOR_MUTED 0x9298A2
#define VP_COLOR_TRACK 0x303238
#define VP_COLOR_HAIRLINE 0x202328
#define VP_COLOR_CLAUDE 0xD97757
#define VP_COLOR_CODEX 0x6F78FF

#endif
